<a href="https://colab.research.google.com/github/sambhajizambre/python-basic/blob/main/cutoff%20project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import datetime
from datetime import date
Data=pd.read_csv('/content/drive/MyDrive/python/project python.csv')
Data

   customer ID           brand        Date  Brand count
0            1          adidas  01/01/2021            3
1            1            polo  01/01/2021            1
2            2           levis  02/01/2021            2
3            2  tomy hilfigure  02/01/2021            1
4            2            nike  03/01/2021            4
5            2            puma  03/01/2021            4

In [11]:
data1=Data.groupby(['customer ID', 'Date']).agg(max=('Brand count', 'max'),total=('Brand count', 'sum')).reset_index()
data1

   customer ID        Date  max  total
0            1  01/01/2021    3      4
1            2  02/01/2021    2      3
2            2  03/01/2021    4      8

In [18]:
data1['Percentage cutoff']= (data1['max']/data1['total'])*100
data1

KeyError: ignored